#!/usr/bin/env bash
# This script handles SIGTERM signal
# Infinite loop with message and sleep
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
