#!/usr/bin/env bash
# This script uses a while loop to read the file line by line
while IFS=: read -r username _ uid gid gecos home shell
do
    IFS=',' read -r _ _ _ info <<< "$gecos"

    IFS=: read -r _ password _ <<< "$(grep "^$username:" /etc/shadow)"

    echo "The user $username is part of the group $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
