#!/usr/bin/env bash
# This script groups visitors by IP and
# HTTP status code and display the data

logfile="apache-access.log"
awk '{print $1, $9}' "$logfile" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
