#!/usr/bin/env bash
# This script uses a while loop to iterate through hour and minutes
h=0
m=1

while [ $h -le 12 ] && [ $m -le 59 ]
do
    printf $h $m
    ((m++))

    if [ $m -eq 60 ]; then
        m=1
        ((h++))
    fi
done | head -n 70
